/**
 * Scheduling Service
 *
 * Matches a classified job to eligible workers and returns a list of bookable
 * time slots, sorted deterministically so the same inputs always produce the
 * same output (important for demo predictability and idempotent re-calls).
 *
 * Matching criteria:
 *   1. Worker must be active.
 *   2. Worker skill must match job's required_skill.
 *   3. Worker must have at least one availability_window that overlaps the
 *      search horizon (now → now + SEARCH_HORIZON_HOURS).
 *
 * Slot generation:
 *   - Slots are generated by slicing each availability window into fixed-length
 *     blocks (SLOT_DURATION_MINUTES, default 120 min / 2 hours).
 *   - Any block that overlaps an active reservation or a confirmed job for the
 *     same worker is excluded.
 *   - Slots starting in the past (before now) are excluded.
 *   - For emergency jobs the search horizon is collapsed to the next 24 hours.
 *   - For same_day jobs the horizon is 48 hours.
 *   - For scheduled jobs the horizon is configured (default 14 days).
 *
 * Deterministic ordering:
 *   - Slots are sorted by starts_at ascending, then by worker name ascending.
 *     This means the earliest slot across all eligible workers is always first.
 *
 * The function is pure (no DB side effects) — it only reads. Reservation
 * creation is handled by the ReservationService.
 */

import { appConfig } from "@/config/app-config";
import { createSupabaseServiceClient } from "@/server/supabase/client";
import type { Urgency, WorkerSkill } from "@/domain/types";

// ─── Constants ────────────────────────────────────────────────────────────────

/** Duration of each generated slot in minutes. */
export const SLOT_DURATION_MINUTES = 120;

/** Search horizons by urgency (hours ahead from now). */
export const SEARCH_HORIZON_HOURS: Record<Urgency, number> = {
  emergency: 24,
  same_day: 48,
  scheduled: appConfig.reservationHoldMinutes < 60
    ? 14 * 24   // fallback 14 days in hours
    : 14 * 24,  // 14 days
};

// ─── Public types ─────────────────────────────────────────────────────────────

export type BookableSlot = {
  workerId: string;
  workerName: string;
  startsAt: Date;
  endsAt: Date;
};

export type GetAvailableSlotsResult =
  | { success: true; slots: BookableSlot[] }
  | {
      success: false;
      error: "job_not_found" | "not_classified" | "db_error";
      message: string;
    };

// ─── Internal types (DB rows) ─────────────────────────────────────────────────

type WorkerRow = {
  id: string;
  name: string;
  skill: WorkerSkill;
  active: boolean;
  availability_windows: Array<{ starts_at: string; ends_at: string }>;
};

type ActiveReservationRow = {
  worker_id: string;
  starts_at: string;
  ends_at: string;
};

type ConfirmedJobRow = {
  assigned_worker_id: string;
  selected_slot_starts_at: string;
  selected_slot_ends_at: string;
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns true if [aStart, aEnd) overlaps [bStart, bEnd). */
export function overlaps(
  aStart: Date,
  aEnd: Date,
  bStart: Date,
  bEnd: Date,
): boolean {
  return aStart < bEnd && aEnd > bStart;
}

/**
 * Slice a window [windowStart, windowEnd) into fixed-length slot blocks,
 * returning only blocks that start on or after `earliest` and before `horizon`.
 */
export function generateSlots(
  windowStart: Date,
  windowEnd: Date,
  slotDurationMs: number,
  earliest: Date,
  horizon: Date,
): Array<{ startsAt: Date; endsAt: Date }> {
  const slots: Array<{ startsAt: Date; endsAt: Date }> = [];
  // Snap the first candidate to the start of the window
  let cursor = new Date(windowStart);

  while (cursor < windowEnd && cursor < horizon) {
    const slotEnd = new Date(cursor.getTime() + slotDurationMs);

    // Slot must fit entirely within the availability window
    if (slotEnd > windowEnd) break;

    // Slot must not start before the earliest allowed time (now)
    if (cursor >= earliest) {
      slots.push({ startsAt: new Date(cursor), endsAt: new Date(slotEnd) });
    }

    cursor = new Date(cursor.getTime() + slotDurationMs);
  }

  return slots;
}

// ─── Core function ────────────────────────────────────────────────────────────

/**
 * Return bookable slots for a classified job.
 *
 * @param jobId - jobs.id to find slots for.
 * @param now   - Reference time (injectable for testing; defaults to Date.now()).
 */
export async function getAvailableSlots(
  jobId: string,
  now: Date = new Date(),
): Promise<GetAvailableSlotsResult> {
  const supabase = createSupabaseServiceClient();

  // 1. Load the job
  const { data: job, error: jobError } = await supabase
    .from("jobs")
    .select("id, required_skill, urgency, service_business_id")
    .eq("id", jobId)
    .single();

  if (jobError || !job) {
    return {
      success: false,
      error: "job_not_found",
      message: `Job not found: ${jobId}`,
    };
  }

  const { required_skill: requiredSkill, urgency, service_business_id: businessId } = job as {
    required_skill: WorkerSkill | null;
    urgency: Urgency | null;
    service_business_id: string;
  };

  if (!requiredSkill || !urgency) {
    return {
      success: false,
      error: "not_classified",
      message: "Job must have required_skill and urgency set before scheduling. Run the Classification Service first.",
    };
  }

  // 2. Compute the search horizon
  const horizonHours = SEARCH_HORIZON_HOURS[urgency];
  const horizon = new Date(now.getTime() + horizonHours * 60 * 60 * 1000);
  const slotDurationMs = SLOT_DURATION_MINUTES * 60 * 1000;

  // 3. Load active workers with matching skill + their availability windows
  //    that overlap the search horizon.
  const { data: workers, error: workerError } = await supabase
    .from("workers")
    .select(`
      id,
      name,
      skill,
      active,
      availability_windows!inner(starts_at, ends_at)
    `)
    .eq("service_business_id", businessId)
    .eq("skill", requiredSkill)
    .eq("active", true)
    .lt("availability_windows.starts_at", horizon.toISOString())
    .gt("availability_windows.ends_at", now.toISOString());

  if (workerError) {
    return {
      success: false,
      error: "db_error",
      message: `Failed to load workers: ${workerError.message}`,
    };
  }

  const workerRows = (workers ?? []) as WorkerRow[];

  if (workerRows.length === 0) {
    return { success: true, slots: [] };
  }

  // 4. Load active reservations for these workers in the search window
  const workerIds = workerRows.map((w) => w.id);

  const { data: reservations, error: resError } = await supabase
    .from("reservations")
    .select("worker_id, starts_at, ends_at")
    .in("worker_id", workerIds)
    .in("status", ["held", "confirmed"])
    .lt("starts_at", horizon.toISOString())
    .gt("ends_at", now.toISOString());

  if (resError) {
    return {
      success: false,
      error: "db_error",
      message: `Failed to load reservations: ${resError.message}`,
    };
  }

  // 5. Load confirmed jobs with assigned_worker_id in these workers
  const { data: confirmedJobs, error: jobsError } = await supabase
    .from("jobs")
    .select("assigned_worker_id, selected_slot_starts_at, selected_slot_ends_at")
    .in("assigned_worker_id", workerIds)
    .eq("status", "confirmed")
    .lt("selected_slot_starts_at", horizon.toISOString())
    .gt("selected_slot_ends_at", now.toISOString());

  if (jobsError) {
    return {
      success: false,
      error: "db_error",
      message: `Failed to load confirmed jobs: ${jobsError.message}`,
    };
  }

  const activeReservations = (reservations ?? []) as ActiveReservationRow[];
  const confirmedJobRows = (confirmedJobs ?? []) as ConfirmedJobRow[];

  // Build per-worker busy period maps
  const busyByWorker = new Map<string, Array<{ start: Date; end: Date }>>();
  for (const r of activeReservations) {
    const periods = busyByWorker.get(r.worker_id) ?? [];
    periods.push({ start: new Date(r.starts_at), end: new Date(r.ends_at) });
    busyByWorker.set(r.worker_id, periods);
  }
  for (const j of confirmedJobRows) {
    if (!j.assigned_worker_id || !j.selected_slot_starts_at || !j.selected_slot_ends_at) continue;
    const periods = busyByWorker.get(j.assigned_worker_id) ?? [];
    periods.push({
      start: new Date(j.selected_slot_starts_at),
      end: new Date(j.selected_slot_ends_at),
    });
    busyByWorker.set(j.assigned_worker_id, periods);
  }

  // 6. Generate candidate slots, filter out busy periods
  const allSlots: BookableSlot[] = [];

  for (const worker of workerRows) {
    const busyPeriods = busyByWorker.get(worker.id) ?? [];

    for (const window of worker.availability_windows) {
      const windowStart = new Date(window.starts_at);
      const windowEnd = new Date(window.ends_at);

      const candidates = generateSlots(windowStart, windowEnd, slotDurationMs, now, horizon);

      for (const candidate of candidates) {
        const isBusy = busyPeriods.some((bp) =>
          overlaps(candidate.startsAt, candidate.endsAt, bp.start, bp.end),
        );
        if (!isBusy) {
          allSlots.push({
            workerId: worker.id,
            workerName: worker.name,
            startsAt: candidate.startsAt,
            endsAt: candidate.endsAt,
          });
        }
      }
    }
  }

  // 7. Deterministic sort: earliest first, then by worker name for tiebreaking
  allSlots.sort((a, b) => {
    const timeDiff = a.startsAt.getTime() - b.startsAt.getTime();
    if (timeDiff !== 0) return timeDiff;
    return a.workerName.localeCompare(b.workerName);
  });

  return { success: true, slots: allSlots };
}
